# fly.toml file generated for nosleepautobot-staging on 2022-09-04T22:46:52-04:00

app = "nosleepautobot-staging"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  dockerfile = "Dockerfile"

[env]
  AUTOBOT_IGNORE_OLD_POSTS = "true"
  AUTOBOT_IGNORE_OLDER_THAN = "1800"
  AUTOBOT_POST_TIMELIMIT = "3600"
  AUTOBOT_ENFORCE_TIMELIMIT = "true"
  AUTOBOT_SUBREDDIT = "caneles"
  AUTOBOT_USER_AGENT = "/r/nosleep AutoBot v20220920 (by /u/SofaAssassin)"
  DEVELOPMENT_MODE = "false"
  ORG="sofaworks"

[experimental]
  allowed_public_ports = []
  auto_rollback = true
