# fly.toml file generated for nosleepautobot-prod on 2022-09-05T00:45:59-04:00

app = "nosleepautobot-prod"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  dockerfile = "Dockerfile"

[[services]]
  http_checks = []
  internal_port = 8686

[env]
  AUTOBOT_IGNORE_OLD_POSTS = "true"
  AUTOBOT_IGNORE_OLDER_THAN = "43200"
  AUTOBOT_POST_TIMELIMIT = "86400"
  AUTOBOT_ENFORCE_TIMELIMIT = "true"
  AUTOBOT_SUBREDDIT = "nosleep"
  AUTOBOT_USER_AGENT = "/r/nosleep AutoBot v20240512 (by /u/SofaAssassin)"
  DEVELOPMENT_MODE = "false"
  ORG="sofaworks"

[experimental]
  allowed_public_ports = []
  auto_rollback = true
