version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          command: |
            pip install -r requirements.dev.txt
            python -m unittest discover autobot/tests
